param([Parameter(Mandatory)][string]$Rid,[Parameter(Mandatory)][string]$PublishDir,[Parameter(Mandatory)][string]$NodeArchive,[Parameter(Mandatory)][string]$OutputDir)
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$inputs=Get-Content (Join-Path $root 'eng/release-inputs.json')|ConvertFrom-Json;$node=$inputs.node.distributions.$Rid
if(!$node){throw "Unsupported RID $Rid"};$actual=(Get-FileHash $NodeArchive -Algorithm SHA256).Hash.ToLowerInvariant();if($actual -ne $node.sha256){throw "Node archive checksum mismatch"}
foreach($p in $inputs.hashes.PSObject.Properties){$h=(Get-FileHash (Join-Path $root $p.Name) -Algorithm SHA256).Hash;if($h -ne $p.Value){throw "Pinned payload mismatch: $($p.Name)"}}
$stage=Join-Path $OutputDir "stage-$Rid";Remove-Item $stage -Recurse -Force -ErrorAction Ignore;New-Item $stage -ItemType Directory -Force|Out-Null
if($Rid -eq 'win-x64'){$payload=Join-Path $stage 'Expedient-AI-Bridges';New-Item $payload -ItemType Directory -Force|Out-Null;Copy-Item (Join-Path $PublishDir '*') $payload -Recurse -Force;New-Item (Join-Path $payload 'app'),(Join-Path $payload 'runtime') -ItemType Directory -Force|Out-Null;Copy-Item (Join-Path $root 'bridge/app/*.js') (Join-Path $payload 'app');Copy-Item (Join-Path $root 'bridge/config.env.example') (Join-Path $payload 'config.env.example');Copy-Item (Join-Path $root 'packaging/windows/install.ps1') $payload;$nodeDir=Join-Path $OutputDir 'node';if(!(Test-Path (Join-Path $nodeDir $node.member))){Expand-Archive $NodeArchive $nodeDir -Force};Copy-Item (Join-Path $OutputDir "node/$($node.member)") (Join-Path $payload 'runtime/node.exe')}
else{$app=Join-Path $stage 'Expedient AI Bridges.app';$mac=Join-Path $app 'Contents/MacOS';New-Item (Join-Path $mac 'app'),(Join-Path $mac 'runtime') -ItemType Directory -Force|Out-Null;Copy-Item (Join-Path $PublishDir 'ExpedientBridges') $mac;Copy-Item (Join-Path $root 'bridge/app/*.js') (Join-Path $mac 'app');Copy-Item (Join-Path $root 'bridge/config.env.example') (Join-Path $mac 'config.env.example');Copy-Item (Join-Path $root 'packaging/macos/Info.plist') (Join-Path $app 'Contents/Info.plist');tar -xzf $NodeArchive -C $OutputDir;Copy-Item (Join-Path $OutputDir $node.member) (Join-Path $mac 'runtime/node');chmod +x (Join-Path $mac 'ExpedientBridges');chmod +x (Join-Path $mac 'runtime/node')}
$epoch=[DateTimeOffset]::FromUnixTimeSeconds([int64](git -C $root show -s --format=%ct HEAD)).UtcDateTime;Get-ChildItem $stage -Recurse|ForEach-Object{$_.LastWriteTimeUtc=$epoch}
$files=Get-ChildItem $stage -File -Recurse|Sort-Object FullName|ForEach-Object{[ordered]@{path=$_.FullName.Substring($stage.Length+1).Replace('\','/');size=$_.Length;sha256=(Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()}}
[ordered]@{product=$inputs.product;version=$inputs.version;rid=$Rid;commit=(git -C $root rev-parse HEAD);sourceDateEpoch=([DateTimeOffset]$epoch).ToUnixTimeSeconds();files=$files}|ConvertTo-Json -Depth 6|Set-Content (Join-Path $stage 'release-manifest.json') -Encoding UTF8
Write-Output $stage
